### ISSUE TITLE
TODO and Emoji-Shortcut dont work together

### ISSUE THREAD

**Issue by josephbergner** [daviddavo/logseq-emoji-shortcodes#3]
Hi,
thanks for integrating emoji-shortcuts. Unfortunaly the parsing of smiley and TODO/DONE in one line will not work perfectly together.  The problem is, that the TODO checkbox is not parsed anymore when you are using emoji-shortcut within the line.

**Expected behaviour:** 
Input:
* TODO something needs to be done <:smile:>

Output after parsing:
* [ ]  [[TODO]] something needs to be done :smile: 

**actual behaviour:**
Output after parsing:
* [[TODO]] something needs to be done :smile: 

I tried my best to imitate logseq with github :smiley: 
Joseph

**Comment by daviddavo** [comment]
It's true, it seems that the square is not rendered. I'll check it out.

![image](https://github.com/daviddavo/logseq-emoji-shortcodes/assets/10263941/9910cb42-0a99-4a2c-8d0d-7cb764eb7744)

**Comment by daviddavo** [comment]
Seems to be fixed now
