### ISSUE TITLE
Tip: A Quick Reference Guide

### ISSUE THREAD

**Issue by chriscz** [daviddavo/logseq-emoji-shortcodes#5]
Thank you for this excellent plugin. It's great that it doesn't need to make any network connections to work.

I needed a quick reference so I generated one with some `jq` filtering.

Here's the script and the output if anyone is interested

**Code**
```
(echo '```' > quickref.md &&  curl -s https://raw.githubusercontent.com/DailyBotHQ/universal-emoji-parser/main/src/lib/emoji-lib.json | jq 'to_entries | .[] | "\(.key) -> \(.value.keywords  | join(", "))"' -r >> quickref.md; echo '```' >> quickref.md)
```

**Example Output**
```
😀 -> grinning_face, face, :D, grin
😃 -> grinning_face_with_big_eyes, happy, haha, :)
😄 -> grinning_face_with_smiling_eyes, joy, funny
😁 -> beaming_face_with_smiling_eyes, kawaii
😆 -> grinning_squinting_face, lol, satisfied, glad, XD
😅 -> grinning_face_with_sweat, hot, laugh, relief
🤣 -> rolling_on_the_floor_laughing, rolling, floor, laughing, rofl
```

**Gist**
https://gist.github.com/chriscz/6ccd217796b0e088f9d63bdad60df83f

Now move it into your LogSeq directory or paste it into a page

_PS: I tried importing it into LogSeq, without using the code backticks and it bombed out!_

**Comment by daviddavo** [comment]
I added it to the README
