### ISSUE TITLE
Priorities of synonyms are .. confusing? backward?

### ISSUE THREAD

**Issue by ipsquiggle** [daviddavo/logseq-emoji-shortcodes#6]
Hi, I'm not exactly sure what the problem is, but I noticed that a lot of the time, I get an unexpected emoji rather than a standard one. Examples:

`:coffee:` makes 🤎 instead of ☕
`:wink:` makes 😜 instead of 😉
`:thinking:` makes 💭 instead of 🤔

I don't think any of those are "wrong", but it feels like it's choosing the "worse option" instead of the "better option".

It's so consistent that I'm wondering if there's just a sort somewhere that's backwards?

This is using `v1.0.1` of this plugin installed through the marketplace, on logseq `v0.10.9`.

Let me know if I can provide any more info.

**Comment by daviddavo** [comment]
I'm using a library called [universal-emoji-parser](https://github.com/DailyBotHQ/universal-emoji-parser).

You can find the list of slugs [here](https://github.com/DailyBotHQ/universal-emoji-parser/blob/main/src/lib/emoji-lib.json).

I think they made some changes to fix errors like the `:coffee:` one, but using one thinking emoji or other might just be a stylistic choice.\

I could not find any library that provided the mappings of the github shortcodes, which I think could be a good standard. If anyone knows a library like that, let me know.

In the meantime, I will update the library version.

**Comment by daviddavo** [comment]
Yeah, updating the deps seems to have fixed the `:coffee:` issue, but the other ones are just stylistic choices by that library.

I'll close the issue, but if someone knows some other library, please let me know.

**Comment by ipsquiggle** [comment]
Ah I see looking closely through the list of keywords, that my examples (plus others I've encountered) are simply due to differences between myself and the authors of that library what good synonyms are (e.g. 🤔 is "think", but not "thinking").

Thank you for investigating this! 🙏
